version: '3.8'
services:
  nest-auth-db:
    image: postgres:15
    container_name: nest-auth-db-container
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - nest-auth-db-data:/var/lib/postgresql/data
    networks:
      - nest-auth-network

  nest-auth-srv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-auth-srv-container
    env_file:
      - .env
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    depends_on:
      - nest-auth-db
    networks:
      - nest-auth-network

volumes:
  nest-auth-db-data:

networks:
  nest-auth-network:
    driver: bridge
